### ISSUE TITLE
Max capacity

### ISSUE THREAD

**Issue by leadinglocally** [HouzuoGuo/tiedot#104]
Hi, been using tiedot for a couple of weeks.

Was using bolt but write performance fell off a cliff after 10-20 million items.

Tiedot has much better write performance, but I read it was only suitable for upto 10 milion items.

It is also blocking my program from startup, I have a ten minute wait while tiedot iterates over the columns to call their load methods. I was thinking this is an easy fix, just making it concurrent, I dont mind contributing if you think that will be possible, and would like me to submit a pull request.

I have more scalability issues to discuss potentially also. At the moment I am storing 6 million items, running on a 32core google compute server with 200 GB ram.

Great repo, thanks.

**Comment by gertcuykens** [comment]
ping @HouzuoGuo :)

**Comment by HouzuoGuo** [comment]
Hello!

Sorry about that, such long delay should not have happened, I am very surprised that it is taking several minutes to load the files. Here is the most time consuming operation in the entire sequence of loading collections:
https://github.com/HouzuoGuo/tiedot/blob/master/data/file.go#L55
It bi-sects the file buffer to find out how much space is in-use, the function "LooksEmpty" looks for consecutive 1024 zeros in the buffer position to determine if the location is in use.

Could you please elaborate on:
- How many collections and indexes are there?
- How large are the collection data and index files?

Could you please also paste the startup log, I am especially interested in the "opened x of x bytes in-use" lines, and the timestamp of those messages.

**Comment by HouzuoGuo** [comment]
Happy good Friday btw.

**Comment by leadinglocally** [comment]
Unfortunately we have had to discontinue use of all third party storage solutions.
So I don't have the codebase any longer to provide the feedback you need.
Thank you for your response regardless.
