### ISSUE TITLE
How to fetch documents sorted by a key and paginate them (Embedded API)

### ISSUE THREAD

**Issue by yaa110** [HouzuoGuo/tiedot#105]
Consider a collection of 100,000 documents of _BOOKS_. How could I `ORDER` books `BY` _PUBLISH YEAR_ key and paginate them using `LIMIT` and `SKIP`?

**Comment by gertcuykens** [comment]
What I do is build index views in memorie so I can do al ordering and searching in golang and only the things I want to store or get from disk I use something else like tiedot. Tiedot is like vim, it can only do one thing really good :)

**Comment by yaa110** [comment]
Yes, it is really good in **storing documents**. I did a benchmark test, Tiedot inserted 100,000 documents in ~0.5 seconds while postgreSQL inserted 100,000 rows in ~7 seconds!

**Comment by gertcuykens** [comment]
Anyway if you take the time to come up with something like most nosql developers had to figure out at some point, you get horizontal scaling for free. But yes its not obvious.
