### ISSUE TITLE
Slow query examples

### ISSUE THREAD

**Issue by Allendar** [HouzuoGuo/tiedot#106]
I love your document system. Thanks so much for your contribution to the community!

I would like to point out something tho. As many may not benchmark their app but still use `tiedot` they might experience greatly diminished performance due to the way the wiki explains queries [here](https://github.com/HouzuoGuo/tiedot/wiki/Query-processor-and-index). Of course there's nothing _wrong_ with what's explained and it's very cool that you demonstrate a query example as being a `json`-string, which would enable very fast and flexible query instructions from tools that might use the someone's Go app with Tiedot as an API.

But here's the thing, and even tho it's up to the user to decide how they implement code, it's maybe nice to include a faster mechanism to query too by using a direct `array` of `map`s. Look at this small test:

```
func testA(b *testing.B) {
	for i := 0; i < b.N; i++ {
		var query interface{}
		ffjson.Unmarshal([]byte(`[{"eq": "Username", "in": ["username"], "limit": 1}]`), &query)
		queryResult := make(map[int]struct{})
		perror(db.EvalQuery(query, App.Users, &queryResult))

		// Query result are document IDs
		for id := range queryResult {
			_, err := App.Users.Read(id)
			perror(err)
			// fmt.Printf("Query returned document %v\n", readBack)
		}
	}
}
```

On my MacBook Pro this is benchmarking at `11637 ns/op` (11.637ms). Which for API's that don't receive query-parameters from outside their scope is not very good.

Now the literal compiled variation like so:

```
func testA(b *testing.B) {
	for i := 0; i < b.N; i++ {
		query = map[string]interface{}{
		       "eq":    "Username",
		       "in":    []interface{}{"Username"},
		       "limit": 1,
	        }
		queryResult := make(map[int]struct{})
		perror(db.EvalQuery(query, App.Users, &queryResult))

		// Query result are document IDs
		for id := range queryResult {
			_, err := App.Users.Read(id)
			perror(err)
			// fmt.Printf("Query returned document %v\n", readBack)
		}
	}
}
```

Now it's just `490 ns/op` (0.49ms).

Maybe for the less interested in deeper logic (I speak from experience seeing even the better programmers just assuming copy-paste from documentation is the best way to go :P) it might be more handy to show the native variation as that's the _normal_ way to go and then the `json` example afterwards showing there're more _flexible_ ways of building a query with external data.

Just a suggestion tho. Love this nifty document-database so much 👍 Thanks again!

**Comment by gertcuykens** [comment]
I suggest you make a pull request and include a second query benchmark in the source code

https://github.com/HouzuoGuo/tiedot/blob/master/benchmark.go#L81

So Howard can merge it.

**Comment by HouzuoGuo** [comment]
Good point! JSON serialisation indeed consumes way more time than the data structures. Please feel free to edit the wiki pages to point this out with your code example.

**Comment by Allendar** [comment]
I've added the example to the Wiki. Thanks for your response!
