### ISSUE TITLE
Slices magically guessed on Read?

### ISSUE THREAD

**Issue by Allendar** [HouzuoGuo/tiedot#107]
I'm having some issues where I'm not getting back the explicitly defined type inside the data that I Insert.

This code for example:

```
type Userright int

const UserrightAccessControlpanel Userright = 1

_, err = App.Usergroups.Insert(map[string]interface{}{
	"id":         1,
	"created":    time.Now().Unix(),
	"updated":    nil,
	"created_by": 1,
	"updated_by": nil,
	"active":     true,
	"translations": map[string]string{
		"nl": "Beheerders",
		"en": "Administrators",
	},
	"users":      []int{1},
	"userrights": []Userright{UserrightAccessControlpanel},
})
if nil != err {
	panic(err)
}
```

Then if I Read:

```
func userHasUserright(targetUserrightID Userright, targetUserID int) bool {
	queryResult := make(map[int]struct{})
	err := db.EvalQuery("all", App.Usergroups, &queryResult)
	if nil != err {
		panic(err)
	}

	// Query result are document IDs
	for id := range queryResult {
		usergroup, err := App.Usergroups.Read(id)
		if nil != err {
			panic(err)
		}

		if _, ok := usergroup["users"].([]interface{}); !ok {
			continue
		}

		if _, ok := usergroup["userrights"].([]interface{}); !ok {
			continue
		}

		userFound := false
		for _, userID := range usergroup["users"].([]interface{}) {
			if userID == float64(targetUserID) { // TODO :: Why isn't the interface{} `int` again?
				userFound = true
				break
			}
		}

		if !userFound {
			continue
		}

		for _, userrightID := range usergroup["userrights"].([]interface{}) {
			if userrightID == float64(targetUserrightID ) { // TODO :: Why isn't the interface{} `int` again?
				return true
			}
		}
	}

	return false
}
```

As you can see I'm typecasting the `targetUserID` to `float64`. Oddly enough I can't type-hint the slice in the `range` to `[]int`, even tho it was exactly that when inserting it. The `ok` check will be false.

I know structs don't work (yet), but is there some way I can be _more sure_ that the sub-entries I insert stay what they were? It feels a bit _Scrip-Language-ish wonky_ that these automatic conversions happen and I don't want to type-hint around too much, as they are always the parts in my Go-apps where bugs are occurring, when they do.

**Comment by HouzuoGuo** [comment]
Hello!

The behaviour originates from Go JSON library. When it deserialises an arbitrary JSON string without type hints, the following types are used:
- Key-value pairs become map[string]interface{}.
- Strings, booleans, and nulls remain.
- Integers become float64.

I must apologise that I'm little lazy to update tiedot's code at the moment, for your issue there is a workaround possible to avoid manually decoding JSON structure, just implement a function like this:

<pre>
func jsonRemarshal(original interface{}, receiver interface{}) {
	serialised, err := json.Marshal(original)
	if err != nil {
		panic(err)
	}
	json.Unmarshal(serialised, &receiver)
}
</pre>

Define a Usergroup struct with JSON tags, and then 
<pre>
dbRecord, err := App.Usergroups.Read(id)
var userGroup Usergroup
jsonRemarshal(dbRecord, &userGroup)
</pre>

Does that help?

**Comment by Allendar** [comment]
Thanks for your response!

I thought of this solution too, but I'm running a high-velocity API and can't permit these conversions. I think just assuming that I need to explicitly typecast all `int`s from the Tiedot-results is probably good enough. I was just wondering if it was really the JSON serializer that did it or if it might've been logic in the Tiedot code itself.

Don't apologize! We all have our things to do every day. I think GitHub is an amazing place to just being able to let a project go it's course for a few weeks/months and come back to it later when you have time again.

I'm a little surprised tho, that with so many stars on this project, that there is so little contribution from the users. I want to try to invest some time digging through the code the coming weeks as a little side-project and make notes what we could add/change to improve the usability and performance even more .
