### ISSUE TITLE
Query on the insides of a slice?

### ISSUE THREAD

**Issue by Allendar** [HouzuoGuo/tiedot#108]
Let's say I insert this:

```
_, err = App.Usergroups.Insert(map[string]interface{}{
	"id":         1,
	"users":      []int{1, 2, 3, 4},
})
```

How could I query the values in that slice?

If that's not possible, let's say I'm dumping the value in there comma-separated instead, like so:

```
_, err = App.Usergroups.Insert(map[string]interface{}{
	"id":         1,
	"users":    "1,2,3,4,5",
})
```

Could I do a `LIKE`-ish check on that field? Or can you only check the whole value in a Query?

**Comment by HouzuoGuo** [comment]
Hello!

Slice values are individually indexed, if you query for users=1, the record will show up no matter users is a single value or an array that contains 1.

**Comment by Allendar** [comment]
I didn't know you do that, amazing! Do you also know to specify ID's? In the example I showed I could probably do `range-from`-`range-to`, but if the IDs different and sequential then it wouldn't hold up. Can the `"eq"` receive an array too?

**Comment by Allendar** [comment]
I just tried it but it panics saying it needs an index. Does the index require a specific notation to work?

**Comment by Allendar** [comment]
Correction; I just made a little mistake myself. It doesn't panic anymore, but it doesn't find single values.

This doesn't give results:

```
query := map[string]interface{}{
	"eq":   9,
	"in":    []interface{}{DBFieldUsergroupUsers},
	"limit": 1,
}
```

Making it a string neither:

```
query := map[string]interface{}{
	"eq":   "9",
	"in":    []interface{}{DBFieldUsergroupUsers},
	"limit": 1,
}
```

And even making it literally the slice that I inserted as a test doesn't give a result:

```
query := map[string]interface{}{
	"eq":    []int{1, 2, 9, 19},
	"in":    []interface{}{DBFieldUsergroupUsers},
	"limit": 1,
}
```

**Comment by HouzuoGuo** [comment]
Here are the test cases of supported scenarios:

https://github.com/HouzuoGuo/tiedot/blob/master/db/doc_test.go#L25

You see, if everything went well, index should find those values in nested slices/maps with ease.

What does the JSON document look like in the database?

**Comment by Allendar** [comment]
This is the my insertion code:

```
_, err = App.Cols["Usergroups"].Insert(map[string]interface{}{
	DBFieldCreated: time.Now().Unix(),
	// DBFieldUpdated:   nil,
	DBFieldCreatedBy: 1,
	// DBFieldUpdatedBy: nil,
	DBFieldActive: true,
	DBFieldTranslations: map[string]string{
		"nl": "Beheerders",
		"en": "Administrators",
	},
	DBFieldUsergroupUsers:      []int{1, 2, 9, 19},
	DBFieldUsergroupUserrights: []Userright{UserrightAccessControlpanel},
})
if nil != err {
	panic(err)
}
```

This is my fetch code:

```
const DBFieldUsergroupUsers = "users"

query := map[string]interface{}{
	"eq":    1,
	"in":    []interface{}{DBFieldUsergroupUsers},
	"limit": 1,
}
queryResult := make(map[int]struct{})
if err = db.EvalQuery(query, App.Cols["Usergroups"], &queryResult); nil != err {
	panic(err)
}

// Fetch the results
for id := range queryResult {
	readBack, err := App.Cols["Usergroups"].Read(id)
	if nil != err {
		panic(err)
	}
	fmt.Printf("Query returned document %v\n", readBack)
}
```

All the `DBField*` constants are all strings with counter-values in them (1,2,3,4...). I'm controlling both the server and client API, so I'm using constants (Go and TypeScript) to keep the field-names as small as possible on my JSON data transfers.

Not getting any errors. Just no result

**Comment by HouzuoGuo** [comment]
Found the issue! And it's went unnoticed because none of the tests insert documents from hand-crafted structure. Here's the culprit: https://github.com/HouzuoGuo/tiedot/blob/master/db/doc.go#L34

The function did not descend into `[]int{1, 2, 9, 19}` because it is not []interface{}.

I know this is very inconvenient, but keeping in mind always to use `[]interface{}` is error prone, would you mind using JSON serialiser together with JSON tag to avoid potential future mistakes like this?

**Comment by Allendar** [comment]
That works! Thanks so much!

I'll just insert all arrays with `interface{}` like this. Maybe it's still handy to add an `else if` for the `[]int` type in a later stage. Or at least show an `error` to use `[]interface{}`.

**Comment by Allendar** [comment]
Just noticed that doing intersection on multiple indexed arrays also doesn't work:

```
err = App.Cols["Usergroups"].Index([]string{DBFieldUsergroupUsers, DBFieldUsergroupUserrights})
```

```
ffjson.Unmarshal([]byte(`[
	{
		"n": [
			{"in": ["14"], "eq": 9},
			{"in": ["15"], "eq": 27}
		],
	}
]`), &query)
```

But when doing union with them (and indexing on both field separately does work):

```
ffjson.Unmarshal([]byte(`[
	{"in": ["14"], "eq": 9},
	{"in": ["15"], "eq": 27}
]`), &query)
```

**Comment by HouzuoGuo** [comment]
Please clarify, did the intersection query yield no result? How many records did you get out of the union query?

**Comment by Allendar** [comment]
Yes the first query in my previous post gives no results. The second does. I inserted 100k entries into the system. The first query yields no results, the second yields all 100k (they're all clones with some ID's in different positions).

**Comment by HouzuoGuo** [comment]
Please take a look at this example, which seems to work:
<code>
	myDBDir := "/tmp/tiedot_test_embeddedExample"
	os.RemoveAll(myDBDir)
	defer os.RemoveAll(myDBDir)
	myDB, err := db.OpenDB(myDBDir)
	if err != nil {
		panic(err)
	}
	if err := myDB.Create("Feeds"); err != nil {
		panic(err)
	}
	feeds := myDB.Use("Feeds")
	_, err = feeds.Insert(map[string]interface{}{"name": []interface{}{0, 1, 3, 4}})
	if err != nil {
		panic(err)
	}
	_, err = feeds.Insert(map[string]interface{}{"name": []interface{}{1, 2, 4, 5}})
	if err != nil {
		panic(err)
	}
	_, err = feeds.Insert(map[string]interface{}{"name": []interface{}{2, 6, 7}})
	if err != nil {
		panic(err)
	}
	if err := feeds.Index([]string{"name"}); err != nil {
		panic(err)
	}
	var query interface{}
	if err = json.Unmarshal([]byte(`[
    {
        "n": [
            {"in": ["name"], "eq": 1},
            {"in": ["name"], "eq": 2}
        ]
    }
]`), &query); err != nil {
		panic(err)
	}
	queryResult := make(map[int]struct{})
	if err := db.EvalQuery(query, feeds, &queryResult); err != nil {
		panic(err)
	}
	for id := range queryResult {
		readBack, err := feeds.Read(id)
		if err != nil {
			panic(err)
		}
		fmt.Println(readBack)
	}
</code>

**Comment by Allendar** [comment]
Yes that works, yet combining 2 indexes that search in a range fail:

```
if err := feeds.Index([]string{"name", "surname"}); err != nil {
	panic(err)
}
var query interface{}
if err = json.Unmarshal([]byte(`[
{
    "n": [
        {"in": ["name"], "eq": 1},
        {"in": ["surname"], "eq": 102}
    ]
}
]`), &query); err != nil {
	panic(err)
}
```

`panic: Please index name and retry query map[in:[name] eq:1].`

They can't run on a combined index? I'm basing this on my SQL-based BTREE index-logic tho, where combined indexes are faster. Yet Tiedot does provide the option for combined indexes, so I'm wondering why it fails in this case.

**Comment by HouzuoGuo** [comment]
Ah I see what you did there.

The index on `[]string{"name", "surname"}` indexes nested attribute "surname". Instead, you need two separate indexes, one on name, the other one on surname.

**Comment by Allendar** [comment]
Thanks for the help. I'll implement it this way :)
