### ISSUE TITLE
Range timestamp ?

### ISSUE THREAD

**Issue by think-free** [HouzuoGuo/tiedot#109]
**Suppose you have this :** 

http://172.16.11.21:9876/create?col=Historic
http://172.16.11.21:9876/index?col=Historic&path=K
http://172.16.11.21:9876/index?col=Historic&path=TS

**Create documents :** 

http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test","V":3,"TS":1466510455}
http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test2","V":4,"TS":1466510456}
http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test","V":5,"TS":1466510459}
http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test","V":6,"TS":1466510465}

**The query doesn't return any documents :** 

http://172.16.11.21:9876/query?col=Historic&q={"n":[{"eq":"Test","in":["K"]},{"int-from":1466510450,"int-to":1466510460,"in":["TS"]}]}

**But work with small TS :** 

http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test","V":3,"TS":5}
http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test2","V":4,"TS":6}
http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test","V":5,"TS":7}
http://172.16.11.21:9876/insert?col=Historic&doc={"K":"Test","V":6,"TS":20}

http://172.16.11.21:9876/query?col=Historic&q={"n":[{"eq":"Test","in":["K"]},{"int-from":1,"int-to":10,"in":["TS"]}]}

**Running on linux 64bits**

Thanks for your help

**Comment by think-free** [comment]
Limitation seems to be at > 999999

**Comment by HouzuoGuo** [comment]
Hello!

Thanks very much for filing this bug, please try the latest commit on master:
https://github.com/HouzuoGuo/tiedot/commit/52109f80eb947a2659653535ab07e9aeb232ad35

**Comment by think-free** [comment]
Ok, working !
Please edit 32bits branch as well

**Comment by HouzuoGuo** [comment]
done here:
https://github.com/HouzuoGuo/tiedot/commit/9b9062d082a0cdf178bc6d3410595c78655ac3b9

**Comment by HouzuoGuo** [comment]
i think this one is now solved. feel free to come back with questions/suggestions.
