### ISSUE TITLE
Atomic update (like atomic add)

### ISSUE THREAD

**Issue by Komosa** [HouzuoGuo/tiedot#111]
It will be great to have _update_ operation based on _actual_ data (in addition to current _overvrite_-like updates).

For example, atomic increment of given field could be done easily with proposed update.

---
BTW, great project, especially design!

**Comment by Komosa** [comment]
I'm thinking about something like `UpdateBytes(docID int, update func([]byte) ([]byte, error)) error` and `UpdateJSON(docID int, update func(map[string]interface{}) (map[string]interface{}, error)) error` (better names are always welcome).

Untested draft of UpdateBytes: https://gist.github.com/Komosa/25a4fed426685857c7c6424cb2a9ef54

(why _defer_ statement isn't used in doc.go?, it is too expensive?)

**Comment by HouzuoGuo** [comment]
good idea, i'll try to code these functions soon, in the meanwhile please write a unit test for this function, if you have a spare moment.

**Comment by HouzuoGuo** [comment]
btw, regarding usage of defer: you are correct, it carries a quite significant ~20% performance penalty.
