### ISSUE TITLE
cant build for bench

### ISSUE THREAD

**Issue by bsbak** [HouzuoGuo/tiedot#115]
Hello, i'm trying build ur tiedot:

`bsbak@bsbak:~/go/src/github.com/HouzuoGuo/tiedot$ go build main.go`
`./main.go:80: undefined: benchSize`
`./main.go:81: undefined: benchCleanup`
`./main.go:144: undefined: embeddedExample`
`./main.go:147: undefined: benchmark`
`./main.go:149: undefined: benchmark2`
what is that? was look in code, all is fine, but i why cant build?

**Comment by gertcuykens** [comment]
Try `go build` without main

**Comment by bsbak** [comment]
> Try go build without main
works! Why with main.go not work? What difference?

**Comment by gertcuykens** [comment]
`go build main.go` only compiles `main.go`. `go build` compiles everything it finds.
