### ISSUE TITLE
Embedded Use - Document ID and `Find`

### ISSUE THREAD

**Issue by drasko** [HouzuoGuo/tiedot#117]
Hello,
I am reading example for embedded use: https://github.com/HouzuoGuo/tiedot/blob/master/example.go and I am having trouble figuring out two things:
1. Document ID is used every time to manipulate document: https://github.com/HouzuoGuo/tiedot/blob/master/example.go - is this document ID kept inside the document itself? I.e. how do I obtain this document ID in my backend in order to update it in the database?
2. Where is Find()? I.e. how do I look for a document that has X == Y?

**Comment by HouzuoGuo** [comment]
Hello!

The document ID is not kept in the document data itself, there is a dedicated ID hash table in each collection that maintains the association between document ID (unchanging) and document's physical location (changing). The unchanging document ID is in the return value of Insert function:

https://github.com/HouzuoGuo/tiedot/blob/master/example.go#L69

Later the ID will be used to update document content:

https://github.com/HouzuoGuo/tiedot/blob/master/example.go#L84

To execute queries such as X==Y, create an index first:

https://github.com/HouzuoGuo/tiedot/blob/master/example.go#L112

The string slice is a path that leads to the value to index. the example index will find value "example" in:

`{"author": {"name": {"first_name": "example"}}}`

And later on, execute an "eq" query:

https://github.com/HouzuoGuo/tiedot/blob/master/example.go#L138

The query function returns document IDs, then you can retrieve the documents by the returned IDs.

**Comment by HouzuoGuo** [comment]
hi @drasko did the second comment answer all of your questions?

**Comment by drasko** [comment]
@HouzuoGuo yes, thanks. I will close this issue.

**Comment by HouzuoGuo** [comment]
no worries, feel free to come back if you have more questions.
