### ISSUE TITLE
How to insert integer value into tiedot using golang embedded package?

### ISSUE THREAD

**Issue by doraemonext** [HouzuoGuo/tiedot#120]
Follow the example.go, everything's fine. But when I try to insert integer value, there's a problem.

```
data := map[string]interface{}{
	"timestamp": 1234123412,
}
col := p.db.Use(tableName)
docid, _ := col.Insert(data)
```

When I have inserted multiple rows like that, and I want to query with timestamp range. But I found I can get nothing. Then I just try to read one specified row.

```
data, _ := col.Read(docid)
fmt.Println(reflect.TypeOf(data["timestamp"]))
```

The result is `float64`, so the range query cannot work.

I want to know how to insert integer as integer value into tiedot?

Thanks.

**Comment by HouzuoGuo** [comment]
Hello! This is actually a quirk of JSON invented after a floaty & stringy typed javascript. Integers in JSON are stored in 64-bit floating point numbers, which is accurate up to some thousands of trillions. Take a look at this function, in which range lookup is implemented:
https://github.com/HouzuoGuo/tiedot/blob/master/db/query.go
Take note that it expects range boundary numbers in either int or float64.

If you need a hand to further debug your query, please paste the section of code and I'll take a look.

**Comment by HouzuoGuo** [comment]
I hope it worked out well for you. Feel free to come back with more questions.
