### ISSUE TITLE
Merry Christmas and happy new year!

### ISSUE THREAD

**Issue by HouzuoGuo** [HouzuoGuo/tiedot#121]
Merry Christmas and happy new year to all of you 😄

**Comment by omeid** [comment]
Happy New Year Howard.

**Comment by HouzuoGuo** [comment]
Merry Christmas @omeid

**Comment by HouzuoGuo** [comment]
Merry Christmas and happy new year @davesters @gertcuykens  @Dr-Terrible @Komosa @smartrevolution  @NoahShen @tjackiw @nickpresta  @suhdev @lanzafame @zhibinr @dchapes @algebraic-brain @bnyeggen @2pi and all

**Comment by handicraftsman** [comment]
Lol/

**Comment by handicraftsman** [comment]
`;kick #tiedot HouzuoGuo Masshighlight`
I would do that if you'll do that on IRC 🐱

**Comment by HouzuoGuo** [comment]
it's been a good star so far!
