### ISSUE TITLE
how to get a random document

### ISSUE THREAD

**Issue by gsmachado** [HouzuoGuo/tiedot#122]
Hello all,

First of all, this is not a bug or a truly "issue". It's more a question/topic to be clarified.

So, how can I efficiently get a random document from tiedot collections? (assuming that I only rely on the  "docID" itself, and I don't have an additional attribute called "random" storing a random value to be chosen from, using "$gte")

Cheers and thanks in advance!

**Comment by HouzuoGuo** [comment]
Hello!

That's an interesting use case, tiedot supports it but with some limitations.

A collection comprises a number of partitions: https://github.com/HouzuoGuo/tiedot/blob/master/db/col.go#L27

And a partition binds persistent document IDs to their physical location in data file: https://github.com/HouzuoGuo/tiedot/blob/master/data/partition.go#L18

The document ID lookup table has 65535 initial buckets:
https://github.com/HouzuoGuo/tiedot/blob/master/data/hashtable.go#L28

So you could pick a random number with a rather limited range between 0 and len(parts)*65535. Next, navigate to the ID lookup hash table:

    ht := Col.parts[randPart].lookup
    key := randKey & ((1 << HASH_BITS) - 1)
    entryAddr := key*BUCKET_SIZE + BUCKET_HEADER
    if ht.Buf[entryAddr] == 1 {
        docID := binary.Varint(ht.Buf[entryAddr+1 : entryAddr+11])
    } else {
        // Re-pick randPart and randKey and loop until a docID is found
    }

There you have it, a docID randomly picked from a rather limited range.

**Comment by HouzuoGuo** [comment]
I hope your inquiry has been answered, feel free to come back with further questions.
