### ISSUE TITLE
Query to return documents which have a certain property defined

### ISSUE THREAD

**Issue by reederz** [HouzuoGuo/tiedot#123]
How can I query for docs which have a certain property defined?

E.g. say I have the following docs:

doc1
```json
{ "name": "John", "surname": "Doe"}
```

doc2
```json
{ "name": "James" }
```

What query would I write to retrieve a set of documents that have `surname` in them? Namely `{ doc1 }`

**Comment by HouzuoGuo** [comment]
Check this out:

https://github.com/HouzuoGuo/tiedot/wiki/Query-processor-and-index

The {"has": "attrname"} query should do it.

**Comment by reederz** [comment]
I don't know how I missed it. Thank you @HouzuoGuo .

**Comment by HouzuoGuo** [comment]
no worries
