### ISSUE TITLE
Istallation problem undefined: COL_FILE_GROWTH, HT_FILE_GROWTH,...

### ISSUE THREAD

**Issue by Enniari** [HouzuoGuo/tiedot#127]
Dear HouzuoGuo,
When I try to install "tiedot" I got these errors below:

`# github.com/HouzuoGuo/tiedot/data
src/github.com/HouzuoGuo/tiedot/data/collection.go:39: undefined: COL_FILE_GROWTH
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:38: undefined: HT_FILE_GROWTH
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:48: undefined: INITIAL_BUCKETS
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:49: undefined: INITIAL_BUCKETS
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:75: undefined: INITIAL_BUCKETS
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:114: undefined: HashKey
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:125: undefined: HashKey
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:140: undefined: HashKey
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:165: undefined: HashKey
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:188: undefined: INITIAL_BUCKETS
src/github.com/HouzuoGuo/tiedot/data/hashtable.go:188: too many errors
`
My Go version is:
go version go1.7.4 linux/amd64
Please could you give me a hand to resolve this problem. 

All the best

**Comment by HouzuoGuo** [comment]
please try again using the latest master branch, does it now work?

**Comment by HouzuoGuo** [comment]
this is most likely resolved in https://github.com/HouzuoGuo/tiedot/issues/126
