### ISSUE TITLE
Question about queries

### ISSUE THREAD

**Issue by jeromelesaux** [HouzuoGuo/tiedot#128]
Hi 
I have a structure like this : 

`map[string]interface{}{"Title": "my title", "Filenames": ["filepath","of","my","filename","extension"]}`

when I use a query like `[{"eq": "`+pattern+`", "in": ["Filenames"]}]` and if the pattern is "my" for instance, 
The request returns me 0 result.

Do you know how I can write a query returns a result for one match among the string array ? 

Sincerely 

Jerome

**Comment by HouzuoGuo** [comment]
Hello Jerome.

Unfortunately indexes won't be helpful in this use case, may I suggest to use a combination of collection scan (https://github.com/HouzuoGuo/tiedot/blob/master/db/col.go#L129) and `GetIn` function (https://github.com/HouzuoGuo/tiedot/blob/master/db/doc.go#L14) to extract values, and run regex filter on top of it?

**Comment by jeromelesaux** [comment]
Thanks a lot
That's exactly what I'm looking for.

**Comment by HouzuoGuo** [comment]
no worries at all
