### ISSUE TITLE
Performance and capacity?

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [HouzuoGuo/tiedot#129]
I've been testing tiedot to use as an integrated storage options for one of my tools and have noticed issues with performance on inserts

I am testing inserts of 1000 rows at a time be executed concurrently and running this 10,000 times to give a total of 10,000,000 rows, I want to store approximately 120 collections each with 10-20 million or so rows.

I have 12 indexes and that probably makes performance a lot worse, however for every 100k rows I am seeing about a 1.2 second increase in insertion times, as of the 400th iteration we're on 4.5-5s per 1000 rows.

Essentially I'd like to know if tiedot just isnt built for large datasets or if im doing something wrong?

I should also note that I am doing this from a machine with 8 threads available.

**Comment by Ewan-GrandSlam** [comment]
I've definitely nailed it down to the indexes, without any indexes it takes 14 minutes to insert 10 million rows, however a single index alone takes 2-4x longer than the insert time to create

**Comment by HouzuoGuo** [comment]
Hello Evan.

Sorry to hear that tiedot has so far failed to perform beyond 4 millions of records. University professors taught me "scenarios not covered by test case may be assumed not working", and it has indeed happened. I remember having conducted benchmark with 2 millions of records at most.

You are correct in saying that having large number of indexes will greatly impact collection performance, let us try some common database tuning techniques and see if they can help:
- Monitor disk IO activities during the benchmark and look for signs of dirty disk buffer pausing tiedot's memory access, if it has indeed occurred consider slightly increasing "vm.dirty_ratio" and further decrease "vm.dirty_background_ratio". Also, avoid using a feature-rich file system such as btrfs to store tiedot data files.
- Limit gomaxprocs to a smaller number. This may sound counter intuitive, but if disk IO was indeed the bottleneck, freeing up CPU resources for doing busy IO work may actually help.
- Disable [transparent huge pages](https://access.redhat.com/solutions/46111) and [same page merging](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Virtualization_Tuning_and_Optimization_Guide/chap-KSM.html).
- Fix tiedot process onto few cpu cores using [taskset](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Performance_Tuning_Guide/sect-Red_Hat_Enterprise_Linux-Performance_Tuning_Guide-Tool_Reference-taskset.html). Though you computer most likely does not use NUMA, but just keep in mind to avoid using tiedot across different NUMA nodes in other computer systems.
