### ISSUE TITLE
[Q] Array indexing / querying

### ISSUE THREAD

**Issue by dweidenfeld** [HouzuoGuo/tiedot#130]
I have the following structure
```golang
type MyStruct struct {
  ID          string
  Parents []string
}
```

And want execute the following queries (SQL pseudo query syntax):
```SQL
SELECT * FROM MyStruct WHERE ID = ?
```
and
```SQL
SELECT * FROM MyStruct WHERE ? IN Parents
```

Is this possible right now?

**Comment by HouzuoGuo** [comment]
Hello Dominik.

How about placing two indexes, one on path "ID" and the other on path "Parents"? Those indexes make the first query as straight forward as an index value lookup, and the second one can be achieved via individual value lookups or evaluation of union of value lookup results.

Check this out: https://github.com/HouzuoGuo/tiedot/wiki/Query-processor-and-index

**Comment by HouzuoGuo** [comment]
I hope your inquiry has been answered, feel free to come back with further questions.
