### ISSUE TITLE
Reduce an initial size of datastore.

### ISSUE THREAD

**Issue by sttyru** [HouzuoGuo/tiedot#136]
Hello!

My issue linked with [that request](https://github.com/HouzuoGuo/tiedot/issues/124) but different :)

I want to run **tiedot** in a httpd mode at x64 VDS with reduced resources, such as disk space ( is no more dozen megabytes). In that regard, I want to reduce an initial size of datastore. At the moment, almost empty storage have a size in 384 Megabytes (it's contains only a one collection with two records).  Can I to reduce disk space utilization by extremelly low (e.g. 20 Megabytes) and at the same time save a working condition and impressive performance?

Maybe somewhere is available builded bundle with minimal requirements? Or I'll need to rebuild it after I will change some values (e.g. constants)?

Thank you!

**Comment by HouzuoGuo** [comment]
Hello!

To me that was the single most important lesson on "today's constant is tomorrow's variable".

Check out this discussion for tips on altering hash table constants, although the discussion tries to increase hash table size, but using similar technique you can also reduce the hash table size:
https://github.com/HouzuoGuo/tiedot/issues/129

Adjusting collection data file is way easier than hash table, only one line requires an adjustment:
https://github.com/HouzuoGuo/tiedot/blob/master/data/collection64.go#L6

Making hash table's size smaller will slightly reduce performance, but feel free to do so until there's a good performance/file size balance.

**Comment by sttyru** [comment]
Thank you so much for your speedy reply! :+1: 

I will to try to change a value and to rebuild a bundle from sources. In my sorry, I can't found a page describing of building process of software. Does this action require some special settings?

**Comment by HouzuoGuo** [comment]
No worries at all.

tiedot does not use any fancy un-official tool for building, `go build` alone is sufficient.

By the way, after having adjusted the hashtable and collection constants, please run all tests `go test -v ./...` in `data/` package, to ensure that parameters are working.

**Comment by HouzuoGuo** [comment]
Feel free to come back if you have more questions.
