### ISSUE TITLE
slice bounds out of range on struct file 

### ISSUE THREAD

**Issue by jeromelesaux** [HouzuoGuo/tiedot#137]
I use Tiedot as embedded database on a raspberrypi (go version 1.8).
After a while, I got this panic : 
panic: runtime error: slice bounds out of range

goroutine 217 [running]:
github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/data.OpenDataFile(0x10b32cc0, 0x2f, 0x800000, 0x10b32cf0, 0x6096f0, 0x10bfa360)
	/home/jls/godev/src/github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/data/file.go:68 +0x2cc
github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/data.OpenHashTable(0x10b32cc0, 0x2f, 0x4, 0x10b32cc0, 0x2f)
	/home/jls/godev/src/github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/data/hashtable.go:38 +0x8c
github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db.(*Col).load(0x10b7cf00, 0x10b7cf00, 0x0)
	/home/jls/godev/src/github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db/col.go:76 +0x6b4
github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db.OpenCol(0x10cd0ec0, 0x10bff9f2, 0x11, 0x13a08908, 0x0, 0x0)
	/home/jls/godev/src/github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db/col.go:35 +0x68
github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db.(*DB).load(0x10cd0ec0, 0x10cd0ec0, 0x1e0c561)
	/home/jls/godev/src/github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db/db.go:78 +0x31c
github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db.OpenDB(0x109ec2a0, 0x11, 0x60c7c0, 0x13bfa240, 0x0)
	/home/jls/godev/src/github.com/jeromelesaux/photo/vendor/github.com/HouzuoGuo/tiedot/db/db.go:39 +0xcc

I use the tiedot version 3.4.0

How can I fix it ? 

best regards 

Jerome

**Comment by HouzuoGuo** [comment]
Hello Jerome.

Could you please take a look at the size of database directory? I wonder if a file had grown too large. Please check the file size and see if an index or collection data file grew beyond 2GB.

**Comment by jeromelesaux** [comment]
if I check the size of the database directory I have got this : 
 du -sh database_photo.db/
625M	database_photo.db/

161M	albums_collection
4,0K	number_of_partitions
465M	photos_collection

I haven't got a file beyond 2 gb.
Best regards

Jerome

**Comment by jeromelesaux** [comment]
Do you need more informations ? 
Do you need a special use case to reproduce ? 

Best regards 

Jerome

**Comment by jeromelesaux** [comment]
just a last track, I haven't got this panic on linux 64bits.
Jerome

**Comment by HouzuoGuo** [comment]
Could you please use this branch https://github.com/HouzuoGuo/tiedot/tree/issue137 to run the source code, trigger the panic, and capture the log output for an analysis?

**Comment by jeromelesaux** [comment]
of course I'll do.
I'll return the log.
Thanks 
Jerome

**Comment by jeromelesaux** [comment]
[app.zip](https://github.com/HouzuoGuo/tiedot/files/1310065/app.zip)
You will think in the attached file the log generated. 
Best regards 
Jerome

**Comment by HouzuoGuo** [comment]
According to the log, a file's mapping buffer magically disappeared, please pull the latest issue137 branch and collect new logs once again.

**Comment by jeromelesaux** [comment]
this the log file.
[app2.zip](https://github.com/HouzuoGuo/tiedot/files/1310446/app2.zip)

**Comment by HouzuoGuo** [comment]
The log messages are saying that there are possibly two goroutines opening and operating on the database at the same time.

Is it possible for your application to call `OpenDB` once upon initialisation, and re-use the same DB pointer across all web handles?

In addition to that, i fixed a missing error return in issue137 branch, please pull the latest and see what kind of error is returned during the OpenDB sequence.

**Comment by jeromelesaux** [comment]
thanks for your return. I do the modifications in my code.
Jerome

**Comment by jeromelesaux** [comment]
Sorry for the time passed to find the issue origin.
Jerome

**Comment by HouzuoGuo** [comment]
According to the captured log files, your application appears to be a web server that serves an API called `SaveGoogleConfiguration`, which I imagine may be invoked concurrently by web clients. There are traces of logs from what appears to be opening the database twice at the same time, therefore your issue most likely resides in web server application.

Does that sound about right?

**Comment by jeromelesaux** [comment]
you're right.
I recode to use a singleton for connection to the database. No problems occurs until now.
You can close this issue.
Thank you for your answer.
best regards 

Jerome

**Comment by HouzuoGuo** [comment]
No worries, I'm glad it worked.
