### ISSUE TITLE
no init variables

### ISSUE THREAD

**Issue by agoalofalife** [HouzuoGuo/tiedot#150]
https://github.com/HouzuoGuo/tiedot/blob/de5794a60cc20a5e5b3a673d4d20302290854170/main.go#L79

It seems to me but here forgotten variables
```go

var benchSize int 
var benchCleanup bool
```

**Comment by agoalofalife** [comment]
I decided

**Comment by HouzuoGuo** [comment]
many thanks

**Comment by agoalofalife** [comment]
You're welcome
