### ISSUE TITLE
 exclude some files from testing

### ISSUE THREAD

**Issue by agoalofalife** [HouzuoGuo/tiedot#151]
@HouzuoGuo  I think need want to exclude from testing those files :
```
example.go
benchmark.go
```
Not much sense in testing them, you think?

**Comment by HouzuoGuo** [comment]
absolutely agreed!

**Comment by agoalofalife** [comment]
Any ideas how to eliminate?

**Comment by HouzuoGuo** [comment]
just ignore them, i guess.
painfully working around tools to achieve 100% coverage is just redundant.

**Comment by agoalofalife** [comment]
really not much left

**Comment by agoalofalife** [comment]
I moved them into separate folders and excluded from testing
