### ISSUE TITLE
duplicate init

### ISSUE THREAD

**Issue by agoalofalife** [HouzuoGuo/tiedot#154]
https://github.com/HouzuoGuo/tiedot/blob/17a0c77af3023dea58989e78260b97540da7e2fa/db/col.go#L72

is duplicate row 
field hts init here 
https://github.com/HouzuoGuo/tiedot/blob/17a0c77af3023dea58989e78260b97540da7e2fa/db/col.go#L46

**Comment by agoalofalife** [comment]
done https://github.com/HouzuoGuo/tiedot/commit/66910625830d0233da99fb72ae7b806befc09c73

**Comment by HouzuoGuo** [comment]
thanks!
