### ISSUE TITLE
Delete old repository

### ISSUE THREAD

**Issue by agoalofalife** [HouzuoGuo/tiedot#155]
please remove the old repository https://github.com/tiedot/tiedot.github.io
I created a new documentation [new](https://github.com/agoalofalife/tiedot.github.io)

**Comment by HouzuoGuo** [comment]
I've assigned you into collaborator's list at tiedot/tiedot.github.io

**Comment by agoalofalife** [comment]
thanks

**Comment by HouzuoGuo** [comment]
thank You
