### ISSUE TITLE
My ID is storing in scientific notation

### ISSUE THREAD

**Issue by Arthur380** [HouzuoGuo/tiedot#163]
Hello,
I have a problem with the storing of my auto generate ID.
I create my id like that : 

```
docID, err := dashboards.Insert(gin.H{
						"Name":        newDash.Name,
						"Description": newDash.Description,
						"AdminId":     newDash.AdminId,
						"SharedWith":  newDash.SharedWith,
						"UpdatedAt":   newDash.UpdatedAt,
						"Widgets":     newDash.Widgets,
					})
					if err != nil {
						c.JSON(http.StatusInternalServerError,
							gin.H{"error": "Could not dashboard site into DB."})
					}

```
My docID at this moment is ok.

But when i would to recovery this ID in others requests 

```
widget, err := widgets.Read(docId)
test, _ := json.Marshal(widget["Dashboard"])
fmt.Println("ID", string(test))
```

I receive my ID in scientific notation and then i lost the last 3 characters.

Do you know how to disable scientific notation and only have int64?

Excuse me for my English.

Thanks

**Comment by beatscode** [comment]
I'm seeing the same behavior.
7549173353548515989 after insert becomes
7549173353548516000 after read
![image](https://user-images.githubusercontent.com/1777648/50013285-c3c97980-ff8e-11e8-8458-0b32d37c94a9.png)

**Comment by Arthur380** [comment]
I have resolve my issue by doing id = id / 1000 in the Insert function in doc.go
Thanks to this my id has the good size and then is not translate as scientific notation.
