### ISSUE TITLE
Replace bou.ke/monkey

### ISSUE THREAD

**Issue by fabaff** [HouzuoGuo/tiedot#174]
`bou.ke/monkey` doesn't have a proper [license](https://github.com/bouk/monkey/blob/master/LICENSE.md).

I can't tell if this should be funny or not.

```
I do not give anyone permissions to use this tool for any purpose. Don't use it.
```

In any way this is a blocker for packaging `tidot` as RPM. A Fedora package should run checks during the build process and in the current we will not be able to include `bou.ke/monkey` which is a dependency for `tidot`.

Please consider to replace `bou.ke/monkey` with something which has a license. Thanks.

**Comment by HouzuoGuo** [comment]
thanks for noticing the license issue, all test code that use bou.ke/monkey have been removed from master branch.

**Comment by fabaff** [comment]
Thank you for taking care about this.
