### ISSUE TITLE
Tiedot take a lot of storage

### ISSUE THREAD

**Issue by Arthur380** [HouzuoGuo/tiedot#178]
Hello,
 
Recently I discovered that my Tiedot db take a lot of storage at the creation (9.3Go without datas and another one 21Go).
I deploy Tiedot via Kubernetes on a VM 64 bits and I don't understand why Tiedot take too much storage.
Apart from that, the database works well.
Have you already see something like that? What can produce this?

Next you can see a screen of one of my collections.

![collection_storage](https://user-images.githubusercontent.com/45686298/89385222-8e434800-d6ff-11ea-9b12-09753565b8e2.PNG)
 
Regards,
 
Arthur

**Comment by HouzuoGuo** [comment]
Hello, thanks for evaluating tiedot! I'm afraid the tiedot project started as a programming exercise and it is no longer actively maintained, though to address the specific issue you described, please check this out:
https://github.com/HouzuoGuo/tiedot/pull/157
Also please be aware that the parameters once set cannot be changed (sorry!) and the parameters can only be applied in a brand new empty database. There are no safe guards in place for validating the value range.

BTW - please check out my latest open source project https://github.com/HouzuoGuo/laitos

**Comment by Arthur380** [comment]
Thanks for your help it works fine by redefining the file data-config.json
