### ISSUE TITLE
Why 130MB Initial Bucket on windows ? 

### ISSUE THREAD

**Issue by olekukonko** [HouzuoGuo/tiedot#39]
Just curios why `tiedot` need to create initial `130MB` file for `_uid` & `data` on windows. That is `260MB` wasted without a inserting any documents.

**Comment by agozie** [comment]
I have 11 collections, 256Mb for each with no data at all! Some collections will only hold a few entries. This is a major blow to my project.
Any Thoughts?

**Comment by HouzuoGuo** [comment]
@agozie sorry - the size of collection files depends on the number of CPUs on the system:
https://github.com/HouzuoGuo/tiedot/blob/master/db/db.go#L50

I intended for the initial size of collection to depend on GOMAXPROCS, so the line must have been a mistake.

The collection file size could be reduced to 64MB by replacing runtime.NumCPU()) into 1.

**Comment by agozie** [comment]
How will reducing runtime.NumCPU() to one affect performance? Thanks alot.

**Comment by HouzuoGuo** [comment]
Reduce it to one should retain approx.30% in your scenario. Run benchmark ./tiedot -mode=bench to be sure.
