### ISSUE TITLE
Websocket Protocol Spec

### ISSUE THREAD

**Issue by wojons** [HouzuoGuo/tiedot#67]
Websocket Protocol API
===================

Objective
------------
* Streaming of Reads Result Set
* Asynchronous Write Requests.
* Asynchronous Read Requests

Goals
--------
The focus of the WebSocket API is to improve performance of high throughput components of tiedot. For example Being able to request a read cursor for results sets. This will help control memory usage on the client side not needing to accept and decode a large payload. It makes requesting pages and more fluid, and also allows clients to table scan the entire database.

WebSockets will also improve performance of write requests. The biggest feature allows for asynchronous writes to take place the client will be able to wait for an acknowledgment from the database or keep moving forward. This also means large number of writes can be streamed into the database.

Spec
------
All messages sent and received in the WebSocket API will be in JSON format. All messages will follow this basic structure.

```js
{
    "message_id": "abcdefghijklmnopqrstuvwxyz1234567890",
    "collection": "acollection",
    "action": "query",
    "payload": {}
}
``` 

Field | Required | Data Type | Description
------ |-------------|--------------- |--------------
message_id | Yes | String | 36 character long id to keep track of a message, the client is responsible for sending and keeping track of a message_id for response data
message_code | No | Int | This is normally only returned from the server in response to a message sent from the client this code is simular to an HTTP status code to let the client know the if there was an error or not
collection | No  | Array of Strings | This is the name of the collection you want to apply the command to. If the command normal operates on a collection. Arrays are being used now incase of multiple collections being queried
action | Yes | String | The type of action trying to be applied based on the path of the HTTP API
payload | Yes | Object | This is the payload for what every action the command is being used in this message

Typical flow for WebSockets
* Client Connects to special WebSocket Port (The port is user defined on server start)
* Server Will respond with a Connection upgrade moving from HTTP to WebSockets
* Messages can now flow between the client and the socket
* Typically this is the best place for the client to set what ever options it wants the server to use other wise the server will use what ever defaults are being used for that version of the server.

Insert Flow after Connection is established
* Client sends message insert with a unique message ID and a payload as the document they want to be updated.
* Server Creates New Gorutine to Insert the data into the Database With Channel to return Data into Connection Gorutine.
* Whenever the Connection Gorutine get a response from Insert Gorutine it sends a response message with the message_id used by Client, a message_code to indicate error or success, and a payload with a subject of ID with the id in that collection, (If there is an error it will be under field called error in root Object

Options
--------------------
Once the WebSocket is established clients will be able to control the size of the buffer and timeouts.

* Document Buffer: The number of documents the API should buffer before sending a batch to the client
* Buffer Size: Number of bytes the buffer should be before the Server should send the buffer to the client
* Timeout: Number of milliseconds the Server should wait before sending What ever is in the buffer, when documents in the buffer is greater than one.

**Comment by HouzuoGuo** [comment]
This one perhaps will not be done anytime soon, closing it for now.
