### ISSUE TITLE
JWT Authorization API

### ISSUE THREAD

**Issue by gertcuykens** [HouzuoGuo/tiedot#74]
Based on `github.com/dgrijalva/jwt-go` implementation. I was wondering if a generic verification system can be achieved through a `Authorization` header?

The API should just define which kind of tokens `tiedot` expect before it will execute the query.

Generating the tokens itself is done by a separate server following the API specification. The goal of this is that webpages can interact with the database directly by presenting a JWT token in the "Authorization" header using ajax or a websocket.

Not sure if the API can be generic enough to be useful for most security implementations?

(https://github.com/gertcuykens/tiedot)

**Comment by HouzuoGuo** [comment]
webjwt progress has been merged into master. Still open todos:

- Document JWT usage and new APIs
- Remove automatic sha512 hashing on credentials, leave it up to the user.
- Bring back webcp
- More extensive testing

**Comment by gertcuykens** [comment]
JWT Authorization API is completed remaining issues will be handled in new webcp.
