### ISSUE TITLE
关于32位系统

### ISSUE THREAD

**Issue by ntsai** [HouzuoGuo/tiedot#79]
我是使用32位的嵌入式 ARM linux系统，我希望能使用 tiedot，我要怎么配置hashtable.go 这个文件来避免32位2GB的问题呢？

**Comment by HouzuoGuo** [comment]
How's everything? Did you successfully use tiedot on ARM system?

**Comment by HouzuoGuo** [comment]
I hope that tiedot will perform well on your hardware platform. Feel free to come back and ask anything!

**Comment by ntsai** [comment]
已经可以了。 但是 collection scan 没用。 现在是当做 ARM 机子上的数据简单保存。性能可以。
