### ISSUE TITLE
Works with other Language or Process

### ISSUE THREAD

**Issue by rocaltair** [HouzuoGuo/tiedot#83]
I wonder if tiedot can give a mode of fifo implementation.

for example:
in C:
```C
int main(int argc, const char *argv[])
{
		int pid;
		mkfifo(FIFO_PATH, 0600);
		pid = fork();
		if (pid < 0) {
				exit(EXIT_FAILURE);
		}
		if (pid == 0) {
				/*child process*/
				return execl("/path_of_tieddot/tiedot", "-mode", "fifo", "-fifo", FIFO_PATH, NULL);
		} 
		struct sigaction act;
		act.sa_handler = on_child_exit_handle;	/*if tiedot failed or something*/
		sigaction(SIGCHLD, &act, NULL);
		/*parent process*/
		int fifo_fd = open(FIFO_PATH, O_RDWR | O_NONBLOCK);
		for (;;) {
				/*works with tiedot using fifo_fd*/
				const char *json_data = "{\"db\":\"db_path\", ... }";
				write(fd, json_data, strlen(json_data));
				/*read*/
				char buff[BUFF_SIZE+1];
				read(fd, buff, BUFF_SIZE);
		}
		return 0;
}
```

Or tiedot watches plenty of fifo files other than only one.

thanks.

**Comment by HouzuoGuo** [comment]
That would be a really useful addition. How about using unix domain sockets for bi-directional data?

**Comment by rocaltair** [comment]
yeah, you're right. It's a better way to use unix domain sockets.
In that case, we can also fork a new process to start tiedot, and do my own logical things in the parent process.

maybe you need design a protocol, for example:
```json
follow_content_len
{
    "db" : "dbpath",
    "op" : {
         
    }
}
```

considering concurrency and timing sequence, it seems like that there is a long long way to go...
or maybe we can create several channels, and each channel keeps order for the requests and responces?

**Comment by HouzuoGuo** [comment]
The branch "singlethread" uses an IPC approach to provide communication across database servers for sharding; it uses domain sockets and a fairly simple binary protocol, which could be extended to interoperate with C.
"singlethread" could use some more time to get ready though.

**Comment by rocaltair** [comment]
ok, thank you.
