### ISSUE TITLE
Where is webcp?

### ISSUE THREAD

**Issue by omeid** [HouzuoGuo/tiedot#85]
It seems like webcp was deleted in 0239f5d7990719d76ac6a8efb9fdad9eb7973371 without any documentation. Was this intentional?

**Comment by gertcuykens** [comment]
Currently webcp does not display columns that are named id. 

I tried to fix it https://github.com/HouzuoGuo/tiedot/issues/77 but its hidden somewhere deep in the framework. At the moment webcp is not supported anymore we can only include it if at least one developer can support it.

Also now that we have cors support, the new webcp will be standalone I think its makes for a better executable without the html embedded in it.

**Comment by omeid** [comment]
Alright, so I just update [some docs](github.com/HouzuoGuo/tiedot/wiki/Limitations) to reflect that.

I am closing this issue for now but if anyone wants to work on a new webcp, I will be happy to help.

**Comment by mcastilho** [comment]
I kinda like that its gone... Always thought the webcp was a big distraction to the dev team in building up a reputable database core engine...

**Comment by HouzuoGuo** [comment]
Regarding the removal of webcp, I made a note in version history:
https://github.com/HouzuoGuo/tiedot/wiki/Version-History

There were two major difficulties with the webcp application:
- After being built and packaged into RPM, the gorice assets do not load anymore.
- The special handling of document attribute "id" from API version 2 causes some trouble in API version 3. I could not work around it.

You are more than welcomed to renovate the webcp application, and I sincerely appreciate it.
