### ISSUE TITLE
Regular Expression Support

### ISSUE THREAD

**Issue by BRoehrl** [HouzuoGuo/tiedot#90]
Hello!

I was wondering if regular expressions ( as mentioned in #27 ) were still supported? Are there maybe any other ways to use Wildcards in Tiedot?

Best regards
Ben

**Comment by HouzuoGuo** [comment]
I am really sorry, the reason of removing regex support is for performance reason, regex cannot get any help from indexes and therefore it is perhaps better to do it in application code.

**Comment by HouzuoGuo** [comment]
Feel free to come back if you have any more questions.
