### ISSUE TITLE
Need a non-blocking ForEachDoc function.

### ISSUE THREAD

**Issue by Splizard** [HouzuoGuo/tiedot#96]
At the moment the ForEachDoc blocks other database calls. Can we get an additional implementation which is non blocking which passes 1 document ID at a time like this?
```
 ForEachDocId(id int) {
    document := Read(id)
    //do something here
}
```

**Comment by HouzuoGuo** [comment]
i'm afraid that is is a bit difficult to implement. what concrete use case do you have in mind for this operation mode?

**Comment by Splizard** [comment]
I would like to write to every document in a collection, I like the ability to Read the document directly by ID. This can be solved by running ForEachDoc and then storing a slice of ID's.
I would prefer a way to iterate over the ID's without blocking.
Im unsure if this is an ideal method, what makes it difficult?

**Comment by Splizard** [comment]
I can do this but I don't like storing all the ID's in memory everytime I call the function.
```
var users = make(map[int]struct{})
	collection.ForEachDoc(func(id int, docContent []byte) (willMoveOn bool) {
		users[id] = struct{}{}
		return true
	})
	
	for id := range users {
		function(id)
	}
```

**Comment by HouzuoGuo** [comment]
that's a fair point indeed.

the reason of placing a lock in the document partition while iterating over the documents is to prevent shifting of document physical location (by insert/update/delete) while iteration is in progress. 

would you like to consider using https://github.com/HouzuoGuo/tiedot/blob/master/db/col.go#L221 ? this way you have precise control over how many documents are in the iteration at once.

**Comment by HouzuoGuo** [comment]
i hope that the function above is good enough for your usage.

Feel free to come back with more questions.

**Comment by ktw** [comment]
@HouzuoGuo I can't seem to figure out how to use the ForEachDocInPage.
Do you have an example, where each page contains a fixed number of documents?
(Maybe 25 documents or something like that, for use in a webpage with paging)

**Comment by HouzuoGuo** [comment]
In this example, it iterates over approximately 50 documents at a time:

totalPages := col.ApproxDocCount() / 50
for page := 0; page < totalPages; page++ {
    col.ForEachDocInPage(page, totalPages, fun)
}

Due to the nature of hash table, the function does not always guarantee that exactly 50 documents are in the iteration, and the order of documents is unpredicable.

**Comment by ktw** [comment]
My results are very unpredictable with this method.
Maybe my data is broken, but when asked for 15 items per page, it returns something like this:
page 0 = 14 items
page 1 = 5 items
page 2 = 9 items
and so on.
(totalPages := col.ApproxDocCount() / 15)

Is the document order totally random, or is it somewhat predictable between calls?
Maybe I could use the ForEachDoc function instead, then skip and take what I need.

**Comment by HouzuoGuo** [comment]
the order is indeed random, and the number of documents in each iteration is not guaranteed to be accurate. However, iterating through all pages guarantees that all documents are visited.
