### ISSUE TITLE
Documentation update needed, can't do example from documentation

### ISSUE THREAD

**Issue by dmitrysdm** [HouzuoGuo/tiedot#97]
I'am not a programmer, and trying do example from documentation:
When i try Insert document with command: 
PS C:\Users\Administrator> curl.exe --data-ascii doc='{"a": 1,"b": 2}' "http://localhost:8000/insert?col=Feeds"
i have got error:
'{a: 1, b: 2}' is not valid JSON document.

the same message i see, when do commang from documentation with post request on GO

[ `go run json_http_request.go` | done: 2.5871301s ]
URL:  http://localhost:8000/insert?col=Feeds
response Status: 400 Bad Request
response Headers: map[Cache-Control:[must-revalidate] Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff] Date:[Tue, 24 Nov 2015 08:41:32 GMT] Content-Length:[51]]
response Body: Please pass POST/PUT/GET parameter value of 'doc'.

It will be great to add example for interacting with database via golang GET|POST requests

package main

import (
    "bytes"
    "fmt"
    "io/ioutil"
    "net/http"
)

func main() {
    url := "http://localhost:8000/insert?col=Feeds"
    fmt.Println("URL: ", url)

    var jsonStr = []byte(`doc='{"a": 1, "b": 2}'`)
    req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonStr))
    req.Header.Set("X-Custom-Header", "GoRequest")
    req.Header.Set("Content-Type", "application/json")

    client := &http.Client{}
    resp, err := client.Do(req)
    if err != nil {
        panic(err)
    }
    defer resp.Body.Close()

    fmt.Println("response Status:", resp.Status)
    fmt.Println("response Headers:", resp.Header)
    body, _ := ioutil.ReadAll(resp.Body)
    fmt.Println("response Body:", string(body))
}

**Comment by ktw** [comment]
I had similar problems, when trying to post from jQuery.
It worked when the doc object is serialized to the url as query string, like this:
"/insert?col=Test&doc="+JSON.stringify({"Hello":"World!"})

The data object (form data) seems to be ignored, when inserting.
(http://api.jquery.com/jquery.ajax/)

**Comment by HouzuoGuo** [comment]
does powershell strip double quotes from parameter input? the server did not get the document with attribute names quoted, thus it failed to pass JSON.

**Comment by dmitrysdm** [comment]
I confirm, It working correctly even via browser with simple GET request:
http://localhost:8000/insert?col=Feeds&doc={"a": 1, "b": 2}

**Comment by HouzuoGuo** [comment]
btw, for your Go HTTP client, please send the content in form submission(type application/x-www-form-urlencoded).

feel free to come back with more questions.
